method: bayes
name: hyperparameter-sweep-stnet

metric:
  name: accuracy
  goal: maximize

parameters:
  num_layers:
    values: [2, 3, 4, 5]
  hidden_dim:
    values: [16, 32, 64]
  graph_num_head:
    values: [1, 2, 4]
  pool_ratio:
    values: [0.5, 0.7, 0.9]
  num_seed_points:
    values: [2, 4, 6]
  graph_dropout:
    values: [0.9, 0.8, 0.5, 0.2]
  window_size:
    values: [10, 20, 30, 40]
  step_size:
    value: 1
  lstm_hidden_dim:
    values: [16, 32, 64]
  lstm_bidirectional:
    values: [true, false] 
  lstm_num_layers:
    values: [1, 2, 3]
  num_classes:
    value: 3
  fc_dropout:
    values: [0.1, 0.2, 0.3]
  learning_rate:
    values: [0.001, 0.01, 0.1]
  weight_decay:
    values: [0.0001, 0.001, 0.01]
  batch_size:
    values: [16, 32, 64, 128]
