method: bayes
name: hyperparameter-sweep-stnet

metric:
  name: best_val_f1
  goal: maximize

parameters:
  num_layers:
    values: [2, 3, 5]
  hidden_dim:
    values: [8, 16, 32]
  graph_num_head:
    values: [1, 2, 4]
  pool_ratio:
    values: [0.5, 0.7, 0.9]
  window_size:
    values: [10, 30, 50]
  lstm_hidden_dim:
    values: [8, 16, 32]
  lstm_bidirectional:
    values: [true, false] 
  lstm_num_layers:
    values: [1, 2, 3]
  fc_dropout:
    values: [0.3, 0.5, 0.7]
  learning_rate:
    values: [0.001, 0.01, 0.1]
  weight_decay:
    values: [0.0001, 0.001, 0.01]
